@startuml
title: casoDeUsoPoliciaEntraAEdificioEnMismaCiudadDelincuenteYEsteLoAtaca

TestCase -> AlgoThief : entrarAEdficio()
AlgoThief -> Delincuente : atacar()
Delincuente -> Arma : atacar()
Arma -> Delincuente : 1
Delincuente -> AlgoThief : 1
AlgoThief -> Reloj : aumentarHora(1))

@enduml