@startuml
'https://plantuml.com/sequence-diagram
title: testEntrarAEdificioYAvanzarHoras


autonumber
actor ->AlgoThief
AlgoThief -> Policia:cantidadDeEntradas(indice)
Policia -> Ciudad: cantidadDeEntradas(indice)

note right : Se muestra el texto de la pista por pantalla
Ciudad --> Policia: cantidadDeHoras
AlgoThief <-- Policia: cantidadHoras

AlgoThief -> Reloj : avanzarHoras(cantidadDeHoras)

AlgoThief->Policia :consultarPista()
Policia -> Ciudad : consultarPista()
Ciudad -> Edificio: pista()
Ciudad <-- Edificio: pista
Policia <-- Ciudad: pista
AlgoThief <--Policia : pista
actor <--AlgoThief :pista
@enduml
